#docker-compose.yml
version: "3.9"

volumes:
  backend_data:

services:
  frontend:
    image: ghcr.io/syntoxr/shoppinglist-ui:latest
    container_name: shoppinglist-frontend
    ports:
      - 80:80
    hostname: shoppinglist-ui
    environment:
      - API_HOST= http://shoppinglist-be:8080
  
  backend:
    image: ghcr.io/syntoxr/shoppinglist-be:latest
    container_name: shoppinglist-backend
    expose:
     - 8080
    hostname: shoppinglist-be
    volumes:
      - backend_data:/usr/local/server/data