name: Observer

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Angular GitHub CI"]
    types: [completed]

jobs:
  #on-success:
  #runs-on: ubuntu-latest
  #if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #steps:
  #...
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@master
      - name: Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: "${{ secrets.gotify_api_base }}"
          gotify_app_token: "${{ secrets.gotify_app_token }}"
          notification_title: "Build Error"
          notification_message: "Your build was completed with errors."
